// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARIFGdvYptQmKnbwiS_pkbrSJf3Oc4bYM',
    appId: '1:448428748684:android:d8dcc1b331c3ae013f30a9',
    messagingSenderId: '448428748684',
    projectId: 'j9cj-54e50',
    storageBucket: 'j9cj-54e50.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaG_9O7vlWgdu7Z4URljzP5FIjis1R0so',
    appId: '1:996313656381:ios:e217b54f026561c30d0e54',
    messagingSenderId: '996313656381',
    projectId: 'uixmain',
    storageBucket: 'uixmain.firebasestorage.app',
    iosBundleId: 'com.example.logininfirebase',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG_aRIznqAX7NmSeHBhBJ4-P_QLQ_Nb3E',
    appId: '1:448428748684:web:4c14268777fb64ff3f30a9',
    messagingSenderId: '448428748684',
    projectId: 'j9cj-54e50',
    authDomain: 'j9cj-54e50.firebaseapp.com',
    storageBucket: 'j9cj-54e50.firebasestorage.app',
    measurementId: 'G-G90MKE1SC8',
  );

}